"""new table

Revision ID: 001671fa3c3a
Revises: 
Create Date: 2020-06-05 16:29:28.657544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001671fa3c3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_title', sa.Unicode(length=50), nullable=True),
    sa.Column('post_content', sa.Unicode(length=5000), nullable=True),
    sa.Column('post_date_gmt', sa.DateTime(), nullable=True),
    sa.Column('post_excerpt', sa.Unicode(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_post_date_gmt'), 'post', ['post_date_gmt'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_post_date_gmt'), table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###
