"""author config

Revision ID: 04710699abb9
Revises: cccdc924d597
Create Date: 2021-04-05 10:47:49.437790

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '04710699abb9'
down_revision = 'cccdc924d597'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('view', sa.Integer(), nullable=True))
    op.drop_column('fiction', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fiction', sa.Column('author', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=300), nullable=True))
    op.drop_column('author', 'view')
    # ### end Alembic commands ###
