"""add column

Revision ID: 1917bc11fab9
Revises: 22e3ed979e17
Create Date: 2021-03-18 22:43:33.875606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1917bc11fab9'
down_revision = '22e3ed979e17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quote', sa.Column('img', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quote', 'img')
    # ### end Alembic commands ###
