"""counting stars

Revision ID: 1d706da156be
Revises: 67c6d64849b0
Create Date: 2021-04-05 20:42:13.379323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d706da156be'
down_revision = '67c6d64849b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('fiction_count', sa.Integer(), nullable=True))
    op.add_column('fiction', sa.Column('chapter_count', sa.Integer(), nullable=True))
    op.add_column('fiction', sa.Column('quote_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fiction', 'quote_count')
    op.drop_column('fiction', 'chapter_count')
    op.drop_column('author', 'fiction_count')
    # ### end Alembic commands ###
