"""new tag

Revision ID: 23116627bd08
Revises: 6331e84a768a
Create Date: 2021-04-20 10:36:47.496901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23116627bd08'
down_revision = '6331e84a768a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fiction', sa.Column('tag', sa.Unicode(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fiction', 'tag')
    # ### end Alembic commands ###
