"""new table

Revision ID: 2c33d1ef6f13
Revises: 64c88c2c4ba0
Create Date: 2020-06-12 12:53:35.040787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c33d1ef6f13'
down_revision = '64c88c2c4ba0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quizbank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('other_answer_1', sa.Text(), nullable=True),
    sa.Column('other_answer_2', sa.Text(), nullable=True),
    sa.Column('other_answer_3', sa.Text(), nullable=True),
    sa.Column('hint', sa.Text(), nullable=True),
    sa.Column('full_solution', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quizbank')
    # ### end Alembic commands ###
