"""new model

Revision ID: 3bea6f719f7a
Revises: 75393775ac64
Create Date: 2021-03-17 19:14:20.628034

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3bea6f719f7a'
down_revision = '75393775ac64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=160), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('author_page', sa.String(length=160), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=160), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('urllib')
    op.drop_table('food')
    op.drop_table('quizbank')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quizbank',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('question', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('solution', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('other_answer_1', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('other_answer_2', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('other_answer_3', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('hint', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('full_solution', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('food',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('food_name', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('food_nutrient', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('urllib',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('website_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('website_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('website_title_tag', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('website_body_tag', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('chapter')
    op.drop_table('author')
    # ### end Alembic commands ###
