"""author about adding

Revision ID: 6331e84a768a
Revises: 1d706da156be
Create Date: 2021-04-15 10:39:42.464407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6331e84a768a'
down_revision = '1d706da156be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('about', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author', 'about')
    # ### end Alembic commands ###
