"""new init

Revision ID: 64c88c2c4ba0
Revises: 
Create Date: 2020-06-12 12:37:16.272691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64c88c2c4ba0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urllib',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_name', sa.String(length=100), nullable=True),
    sa.Column('website_url', sa.String(length=100), nullable=True),
    sa.Column('website_title_tag', sa.String(length=100), nullable=True),
    sa.Column('website_body_tag', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.Unicode(length=50), nullable=True),
    sa.Column('last_name', sa.Unicode(length=50), nullable=True),
    sa.Column('user_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('engine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_title', sa.Unicode(length=300), nullable=True),
    sa.Column('post_content', sa.Unicode(length=5000), nullable=True),
    sa.Column('post_date_gmt', sa.DateTime(), nullable=True),
    sa.Column('post_excerpt', sa.Unicode(length=500), nullable=True),
    sa.Column('original_link', sa.Unicode(length=300), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engine_post_date_gmt'), 'engine', ['post_date_gmt'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_engine_post_date_gmt'), table_name='engine')
    op.drop_table('engine')
    op.drop_table('user')
    op.drop_table('urllib')
    # ### end Alembic commands ###
