"""author avatar

Revision ID: 67c6d64849b0
Revises: b6da83c6d157
Create Date: 2021-04-05 11:25:35.600037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67c6d64849b0'
down_revision = 'b6da83c6d157'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('img', sa.String(length=240), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author', 'img')
    # ### end Alembic commands ###
