"""new table

Revision ID: 9011cbeff77b
Revises: 855417d40ebb
Create Date: 2020-06-07 17:22:18.007114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9011cbeff77b'
down_revision = '855417d40ebb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urllib',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_name', sa.String(length=100), nullable=True),
    sa.Column('website_url', sa.String(length=100), nullable=True),
    sa.Column('website_title_tag', sa.String(length=100), nullable=True),
    sa.Column('website_body_tag', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('urllib')
    # ### end Alembic commands ###
