"""up date chapter model

Revision ID: ac5a2abe9a18
Revises: 3bea6f719f7a
Create Date: 2021-03-17 19:55:44.762033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac5a2abe9a18'
down_revision = '3bea6f719f7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter', sa.Column('chapter_order', sa.Integer(), nullable=True))
    op.add_column('chapter', sa.Column('fiction', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chapter', 'fiction', ['fiction'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chapter', type_='foreignkey')
    op.drop_column('chapter', 'fiction')
    op.drop_column('chapter', 'chapter_order')
    # ### end Alembic commands ###
