"""author connect to fiction

Revision ID: b6da83c6d157
Revises: 04710699abb9
Create Date: 2021-04-05 11:16:28.961284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6da83c6d157'
down_revision = '04710699abb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('email', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author', 'email')
    # ### end Alembic commands ###
