"""add id

Revision ID: ca851e78787d
Revises: ac5a2abe9a18
Create Date: 2021-03-18 21:04:46.776577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca851e78787d'
down_revision = 'ac5a2abe9a18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fiction', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fiction', 'author', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fiction', type_='foreignkey')
    op.drop_column('fiction', 'author_id')
    # ### end Alembic commands ###
