"""update model

Revision ID: cccdc924d597
Revises: faccae6c7a85
Create Date: 2021-04-04 17:19:19.193881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cccdc924d597'
down_revision = 'faccae6c7a85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fiction', sa.Column('version', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fiction', 'version')
    # ### end Alembic commands ###
