"""new table

Revision ID: ecdd3b452cc3
Revises: 23116627bd08
Create Date: 2021-04-20 12:42:33.970230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecdd3b452cc3'
down_revision = '23116627bd08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fiction_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fiction_id'], ['fiction.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'fiction_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('like')
    # ### end Alembic commands ###
