"""update model

Revision ID: faccae6c7a85
Revises: 209f22d8a886
Create Date: 2021-04-04 17:16:12.918388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faccae6c7a85'
down_revision = '209f22d8a886'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fiction', sa.Column('slug', sa.String(length=160), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fiction', 'slug')
    # ### end Alembic commands ###
